apiVersion: v2
name: nmrxiv-app
description: A  Helm chart of nmrXiv-Laravel Application for K8S.
maintainers:
  - name: Nisha Sharma
    email: nisha.sharma@uni-jena.de

type: application
version: 0.8.0
appVersion: "1.16.0"

dependencies:
# Removed deprecated postgresql dependency - replaced by rdkitcatridgepostgres
- name: redis
  version: "17.6.0"
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: rabbitmq
  version: "11.5.0"
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
- name: meilisearch
  version: "0.1.44"
  repository: https://nfdi4chem.github.io/repo-helm-charts
  condition: meilisearch.enabled
- name: nmrium
  version: "0.1.0"
  repository: https://nfdi4chem.github.io/repo-helm-charts
  condition: nmrium.enabled
- name: rdkitcatridgepostgres
  version: "0.2.0"
  repository: https://nfdi4chem.github.io/repo-helm-charts
  condition: rdkitcatridgepostgres.enabled
- name: nmrkit
  version: "0.2.1"
  repository: https://nfdi4chem.github.io/repo-helm-charts
  condition: nmrkit.enabled
- name: keycloak
  version: "18.3.3"
  repository: https://charts.bitnami.com/bitnami
  condition: keycloak.enabled