apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nmrxiv-app.fullname" . }}
  labels:
    {{- include "nmrxiv-app.labels" . | nindent 4 }}
  annotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
spec:
  {{- if .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nmrxiv-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      # annotations:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      labels:
        {{- include "nmrxiv-app.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: logs
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: testing
          emptyDir: {}
        - name: sessions
          emptyDir: {}
        - name: views
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: caddy_data
          emptyDir: {}
      #serviceAccountName: {{ include "nmrxiv-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: postgres-wait-ready
          image: alpine
          command:
            - sh
            - -c
            - for i in $(seq 1 200); do nc -z -w3 $DB_HOST $DB_PORT && exit 0 || sleep $((2*i)); echo -n "." ; done; exit 1
          envFrom:
            - configMapRef:
                name: {{ .Values.EnvConfigMapRef.name }}
        - name: database-migrations
          image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag | default .Chart.AppVersion }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.EnvConfigMapRef.name }}
            - secretRef:
                name: {{ .Values.EnvSecretRef.name }}
          command:
            - "php"
          args:
            - "artisan"
            - "migrate"
            - "--force"
      containers:
        - name: {{ .Values.appImage.name }}
          imagePullPolicy: {{ .Values.appImage.pullPolicy }}
          image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag | default .Chart.AppVersion }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.EnvConfigMapRef.name }}
            - secretRef:
                name: {{ .Values.EnvSecretRef.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/storage/logs
            - name: cache
              mountPath: /var/www/html/storage/framework/cache
            - name: sessions
              mountPath: /var/www/html/storage/framework/sessions
            - name: views
              mountPath: /var/www/html/storage/framework/views
            - name: testing
              mountPath: /var/www/html/storage/framework/testing
            - name: tmp 
              mountPath: /tmp
            - name: caddy_data
              mountPath: /data/caddy
          ports:
            - containerPort: 80